#此处表示使用dev这个块作为配置
spring:
  profiles:
    active: dev

---

server:
  port: 7777
spring:
  profiles: default

---

server:
  port: 8888
spring:
  profiles: dev

---

server:
  port: 9999
spring:
  profiles: prod

---



#下面的这部分信息是为了注入玩
person:
    lastName: hello@china.com
    age: 18
    boss: false
    birth: 2017/12/12
    maps: {k1: v1,k2: 12}
    lists:
        - lisi
        - zhaoliu
    dog:
        name: 小狗
        age: 12